type SanitizeOptions = {
  channel?: string | null;
  ensureSignature?: boolean;
};

function clean(value: string | undefined) {
  return value?.trim() || "";
}

export function outreachSenderName() {
  return (
    clean(process.env.OUTREACH_SIGNATURE_NAME) ||
    clean(process.env.LEAD_COMMAND_OPERATOR_NAME) ||
    clean(process.env.BOOKING_OWNER_NAME) ||
    "Stephen Burch"
  );
}

export function outreachBrandName() {
  return clean(process.env.OUTREACH_SIGNATURE_BRAND) || "Ghost AI Solutions";
}

export function customerSignature() {
  return `Best,\n${outreachSenderName()}\n${outreachBrandName()}`;
}

export function sanitizeSubject(subject: string | null | undefined) {
  const fallback = "Quick automation idea";
  return (subject || fallback)
    .replace(/^Subject:\s*/i, "")
    .replace(/\[(your name|name|sender name)\]/gi, outreachSenderName())
    .replace(/\[(company name|brand name)\]/gi, outreachBrandName())
    .replace(/\s+/g, " ")
    .trim() || fallback;
}

export function sanitizeInternalReason(reason: string | null | undefined) {
  const value = clean(reason || undefined);
  if (!value) return null;
  if (/ai operator|openai|lead command approval workflow/i.test(value)) {
    return "Prepared for operator approval.";
  }
  if (/rewritten from slack/i.test(value)) return "Rewritten from Slack.";
  return value;
}

export function sanitizeCustomerMessage(message: string | null | undefined, options: SanitizeOptions = {}) {
  const channel = clean(options.channel || undefined).toLowerCase();
  const ensureSignature = options.ensureSignature ?? channel !== "sms";
  let text = clean(message || undefined);

  text = text
    .replace(/\[(your name|name|sender name)\]/gi, outreachSenderName())
    .replace(/\[(company name|brand name)\]/gi, outreachBrandName())
    .replace(/\{(your name|name|sender name)\}/gi, outreachSenderName())
    .replace(/<(your name|name|sender name)>/gi, outreachSenderName());

  const lines = text
    .split(/\r?\n/)
    .filter((line) => !isInternalMetadataLine(line))
    .map((line) => line.replace(/\bGhost Lead Command\b/g, outreachBrandName()));

  text = lines.join("\n").trim();

  if (ensureSignature) {
    text = normalizeEmailSignature(text);
  }

  return text.replace(/\n{3,}/g, "\n\n").trim();
}

function isInternalMetadataLine(line: string) {
  const value = line.trim();
  return (
    /^queued by ai operator/i.test(value) ||
    /^queued from lead command/i.test(value) ||
    /^rewritten from slack/i.test(value) ||
    /^prepared by ai operator/i.test(value) ||
    /^generated by/i.test(value) ||
    /^ai operator/i.test(value)
  );
}

function normalizeEmailSignature(text: string) {
  const signature = customerSignature();
  const lines = text.split(/\r?\n/);
  const signoffIndex = lines.findIndex((line) => /^(best|thanks|thank you|regards),?$/i.test(line.trim()));

  if (signoffIndex >= 0) {
    return [...lines.slice(0, signoffIndex), signature].join("\n");
  }

  if (text.includes(outreachSenderName()) && text.includes(outreachBrandName())) {
    return text;
  }

  return `${text}\n\n${signature}`;
}
