export const policyEffectiveDate = "October 1, 2026";
export type PolicySection = { title: string; paragraphs: string[] };
export const privacySections: PolicySection[] = [
  { title: "Provider and scope", paragraphs: ["Ghost AI Solutions provides Ghost Lead Command and Ghost Director, its AI sales director. This notice covers business inquiries, AI consultation, proposals, billing coordination, campaign operations, and earlier waitlist submissions. Contact support@ghostai.solutions with privacy questions."] },
  { title: "Information processed", paragraphs: ["Depending on the features you use, information can include your business contact details, company, website, services, target market, territory, goals, capacity, and follow-up preferences. AI onboarding saves messages, confirmed and inferred facts, research, recommendations, quotes, proposals, and session activity.", "Campaign records can include business contacts, source evidence, scores, outreach drafts, approvals, delivery events, replies, call tasks and outcomes, suppression preferences, booking handoffs, and reporting. Data can come from customers and public or licensed sources. Public availability does not remove the need for appropriate use.", "Technical records can include visitor and session identifiers, page and referring URLs, UTM parameters, browser information, interaction events, timestamps, and operational logs. An onboarding session identifier is stored in your browser so you can resume a conversation. Do not submit passwords, government identifiers, card details, medical records, or sensitive personal information in chat."] },
  { title: "Purposes and AI processing", paragraphs: ["Information is used to respond to inquiries, research markets, prepare a proposed scope, calculate quotes, coordinate approved campaigns, support follow-up and reporting, honor suppression preferences, and investigate technical or abuse issues. AI-generated information can be inaccurate; review facts and messages before approving activity.", "The consultation can send relevant messages, business facts, and conversation context to the configured AI provider. The code supports OpenAI; enabled behavior depends on deployment configuration. Provider terms and data practices also apply to processing performed by that provider."] },
  { title: "Providers, personnel, and payment", paragraphs: ["Relevant data can be processed by hosting and database providers, research and business-data providers, communications providers, connected CRM systems, and Ghost personnel or service contractors. Enabled integrations determine which providers receive information. Personnel or providers may process information outside your country. Ask support for the providers and processing locations relevant to your proposed service before sharing information with special restrictions.", "Where Stripe checkout is enabled, Stripe collects payment information on its hosted page. The app stores identifiers and statuses needed to associate payments, proposals, and subscriptions. Do not enter card details into the consultation. Information may also be disclosed as required by applicable law or to address misuse and protect rights."] },
  { title: "Communications and optional voice", paragraphs: ["Business contact details are used for your inquiry, plan, support, and requested product communications. Opt out of marketing through the unsubscribe option or support@ghostai.solutions. Billing, service, or suppression records may still be needed after opting out.", "Optional voice reads assistant text using your browser’s speech-synthesis capability. The current consultation does not provide a microphone-recording input. Your browser or speech provider may process text according to its own settings and practices."] },
  { title: "Retention and requests", paragraphs: ["Retention depends on record purpose, the active inquiry or service, billing and contractual requirements, suppression and abuse-prevention needs, and applicable law. This notice does not promise automatic deletion on a fixed schedule. Contact support@ghostai.solutions to request access, correction, deletion, changed communication preferences, or rights available under applicable law. Verification may be needed and some records may need to be retained.", "Customers must have appropriate rights and instructions for records they supply. A business contact receiving campaign outreach can use the message’s opt-out mechanism or contact us with the recipient address and campaign context so we can investigate and route the request."] },
  { title: "Security, external sites, and updates", paragraphs: ["Share only the information needed for the service. No online system can guarantee absolute security. External onboarding, payment, and other linked sites may have separate policies. This service is intended for business use, not collecting information from children. Updates to this notice will show a new effective date."] },
];
export const termsSections: PolicySection[] = [
  { title: "Provider and approved scope", paragraphs: ["Ghost AI Solutions provides Ghost Lead Command. Ghost Director is the AI sales director within the product, not a separate legal entity. You must have authority to act for the business whose information and campaign you submit.", "Consultation is not approval to send outreach or a guarantee that every requested feature can be delivered. Review the proposal’s territory, qualification rules, activity limits, channels, integrations, human support, and exclusions before accepting. Launch requires the agreed approvals and operational readiness. A separately signed agreement controls where it conflicts with these website terms; existing agreements are not rewritten by a website update."] },
  { title: "Setup, monthly prices, and billing", paragraphs: ["Starting monthly prices are Scout $497, Reach $1,250, and Convert $2,500. Base one-time setup fees are $750, $1,500, and $2,500 respectively. Managed is custom-scoped with a quote baseline of $3,500/month and $4,000 setup. Amounts are in USD; any applicable tax and approved additions are shown in the proposal or checkout.", "Base scope includes one campaign and one territory. Extra campaigns, territories, integrations, or activity can increase the quote. Setup and recurring charges are separate. The accepted proposal and checkout determine the actual amount and payment schedule. Existing quotes, subscriptions, discounts, and agreements retain accepted prices unless a change is agreed.", "Review the renewal interval, minimum term, cancellation procedure, refund treatment, and service start date in your proposal or signed agreement before paying. Ask support@ghostai.solutions before acceptance if any item is unclear. This page does not promise a free trial, cancellation of an existing contract, or an unagreed refund. Card details are entered only on Stripe’s hosted checkout."] },
  { title: "Activity definitions and exclusions", paragraphs: ["A qualified prospect is a researched business account meeting the agreed fit and territory criteria with an identified contact path. It is not necessarily an interested buyer, exclusive contact, appointment, or sale. Your proposal defines required evidence and any agreed validation or replacement rules.", "Monthly allowances are maximum included work units, not guaranteed responses or meetings. An outreach unit is one approved email send, including a follow-up. A managed call unit is one human call attempt whether or not someone answers. A phone-assist task does not mean a call was completed. Managed calling responsibility and availability must be confirmed in the proposal.", "Additional researched leads, approved sends, and managed call attempts are quoted at $6, $9, and $12 per unit before approval. Automatic usage-based overage billing is not implemented. Ad spend, third-party subscriptions, extra mailboxes or domains, and custom integration work are excluded unless listed in the proposal."] },
  { title: "Customer responsibilities and acceptable use", paragraphs: ["Provide accurate business information and evidence for offer claims. You are responsible for approvals, lawful instructions, rights to supplied records and accounts, delivery capacity, and follow-up assigned to your team. Do not request impersonation, fabricated claims, evasion of opt-outs, unlawfully obtained data, or unauthorized messages.", "Outreach must follow applicable law and platform rules, including accurate sender identity and appropriate opt-out handling. Ghost may hold activity for human review when information, sender readiness, permissions, or compliance instructions are incomplete, and may pause unsafe or unauthorized activity while discussing remediation."] },
  { title: "AI limitations and results", paragraphs: ["AI research and messages can contain mistakes; third-party contacts can be incomplete or out of date. Human review remains necessary. Outcomes depend on the offer, market, data quality, deliverability, response speed, and sales process. Conversations, appointments, meetings, sales, revenue, and profit are not guaranteed.", "Ghost Director coordinates work and does not replace your judgment or every sales employee. Availability can depend on connected systems and providers. Engagement-specific service levels, remedies, liability limits, and ownership terms belong in your accepted agreement; this page does not invent them."] },
  { title: "Privacy, support, and changes", paragraphs: ["Read the Privacy Notice before submitting information. Contact support@ghostai.solutions for scope, billing, cancellation, data, or support questions. Website updates show a new effective date. Changes to an accepted proposal or agreement follow that agreement’s process; updated website text does not silently replace negotiated terms."] },
];
